### ISSUE TITLE
Color serialization

### ISSUE THREAD

**Issue by malys** [scad-js/scad-js#8]
Hi, 
I'm playing with your project and I think that there is a bug to serialize string as value (ex: color value).
I have fix it like this:
`
const paramsStr = params => Object.entries(params).map(x => {
  console.log(x, typeof x[1])
  if (typeof x[1] === "string") return `${x[0]} = "${stringify(x[1])}"`
  else return `${x[0]} = ${stringify(x[1])}`
}).join(', ');
`
It's working fine. If you want you can integrate this fix and release a new version.
Moreover, I use typescript in my project: https://github.com/malys/openscad-closet.git
It could be a good example for other people

**Comment by 20lives** [comment]
Hi @malys !
I am really excited seeing people trying out this project :)

I can't understand what is the problem with color serialization, can you give an example?

```javascript
cube.color('red');
cube.color('purple', 0.5);
cube.color('#ff3588');
```
all of the examples above works as expected.

I also took your closet project and ran it without any color issues.

**Comment by malys** [comment]
# Description
Without patch:
The generated code is:
`
color(c = white, alpha = 1)
Console: WARNING: Ignoring unknown variable 'white', in file output.scad, line 4.
`

with patch:
`
color(c = "white", alpha = 1)
Console :Good rendering
`

# Environment

* Windows 10

`
$ node -v
v15.3.0
`
`
$ openscad -v
OpenSCAD version 2019.05
`

**Comment by 20lives** [comment]
I can't reproduce this issue using the same node version.
can you please clone this project and paste here the output of `npm run test` ?

**Comment by 20lives** [comment]
Finally found the issue, but your solution breaks up other things.
To test it you can clone this project and run `npm test`

**Comment by malys** [comment]
```
const stringify = x => (typeof x == 'string')
  ? (x == 'undef' || x.includes('$t')) ? x : `"${x}"`
  : JSON.stringify(x).replace(/"/g, '').split(',').join(', ');
```

Reading quickly documentation of openscad, I think that you should replace:
 x.includes('$t')) -> x.startWith('$')
to be generic, no?

**Comment by malys** [comment]
elseif your fix is working well Thanks.

**Comment by 20lives** [comment]
There are other ways to use the animation variable, like the one below:
```javascript
cube(['$t', '2 * $t', 5]).serialize(),
```
